#!/usr/bin/env bash

## Description: Run TYPO3 CLI command inside the web container
## Usage: typo3 [flags] [args]
## Example: "ddev typo3 site:list" or "ddev typo3 cache:flush"
## ExecRaw: true

.build/bin/typo3 "$@"
