services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Zeroseven\Pictureino\:
    resource: '../Classes/*'

  cache.pictureino:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['pictureino']

  Zeroseven\Pictureino\Command\CleanupCommand:
    tags:
      - name: 'console.command'
        command: 'pictureino:cleanup'
        description: 'Cleanup all processed images'
