services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Zeroseven\Pictureino\:
    resource: '../Classes/*'

  Zeroseven\Pictureino\Command\CleanupCommand:
    tags:
      - name: 'console.command'
        command: 'pictureino:cleanup'
        description: 'Cleanup all processed images'

  Zeroseven\Pictureino\Security\ContentSecurityPolicy\InlineScriptPolicyHandler:
    tags:
      - name: event.listener
        identifier: 'pictureino-inline-script'
        event: TYPO3\CMS\Core\Security\ContentSecurityPolicy\Event\PolicyMutatedEvent
