services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Zeroseven\Pictureino\:
    resource: '../Classes/*'

  Zeroseven\Pictureino\Command\CleanupCommand:
    tags:
      - name: 'console.command'
        command: 'pictureino:cleanup'
        description: 'Cleanup all processed images'
