categories:
  Picturerino.settings:
    label: 'Picturerino (Responsive Images)'

settings:
  picturerino.breakpoints:
      type: stringlist
      default:  ['xs: 0', 'sm: 576', 'md: 768', 'lg: 992', 'xl: 1200', 'xxl: 1400']
      category: Picturerino.settings
      label: 'Breakpoints'
      description: 'Define as many breakpoints as you need. The default breakpoints are based on Bootstrap. You can use the following format: "alias: value".'
