categories:
  Pictureino.settings:
    label: 'Pictureino (Responsive Images)'

settings:
  pictureino.breakpoints:
    type: stringlist
    default: ['xs: 0', 'sm: 576', 'md: 768', 'lg: 992', 'xl: 1200', 'xxl: 1400']
    category: Pictureino.settings
    label: 'Breakpoints'
    description: 'Define as many breakpoints as you need. The default breakpoints are based on Bootstrap. You can use the following format: "alias: value".'
  pictureino.maxImageDimensions:
    type: int
    default: '2000'
    category: Pictureino.settings
    label: 'The maximum height or width (px)'
    description: 'The maximum width or height of processed images. This is used to calculate the size of the image. The default value is 2000 (px).'
  pictureino.retina:
    type: bool
    default: 0
    category: Pictureino.settings
    label: 'Retina'
    description: 'Enable retina support. This will create images with double the resolution for retina displays. This is useful for high-resolution displays, but will increase the size of the images.'
  pictureino.debug:
    type: bool
    default: 0
    category: Pictureino.settings
    label: 'Debug'
    description: 'Enable debug mode. This will output additional information in data attributes and ajax requests. This is useful for debugging purposes, but should be disabled in production.'
